# Application configuration

# Data settings
data:
  default_path: "./data/sample_data.csv"
  allowed_formats:
    - csv
    - xlsx
    - json

# LLM settings
llm:
  provider: "ollama"
  default_model: "qwen2.5-coder:7b"
  alternative_models:
    - "codellama:7b"
    - "codellama:13b-code" 
    - "qwen2.5-coder:7b"
    - "codellama:latest"
    - "deepseek-r1:7b-qwen-distill-q8_0"
    - "gemma3:latest"
  temperature: 0.1
  max_tokens: 512
  timeout: 30

# UI settings
ui:
  theme: "light"
  title: "Data Analysis Chatbot"
  sidebar_width: 300
  chart_height: 400
  max_chat_history: 20

# Error handling
errors:
  log_file: "./logs/app.log"
  debug_mode: false